skyflowapi/skyflow-android

.github/workflows/internal_release.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Skyflow/build.gradle, build.gradle, scripts/bump_version.sh, settings.gradle
=> added workflows

app/src/main/java/com/Skyflow/MainActivity.kt, app/src/main/java/com/Skyflow/RevealActivity.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
1. Made changes to sample app appearance.
2. Added CVV field to collect and reveal flow.
=> Changes to sample code

Skyflow/src/main/kotlin/Skyflow/CollectContainer.kt, Skyflow/src/main/kotlin/Skyflow/CollectElementInput.kt, Skyflow/src/main/kotlin/Skyflow/CollectOptions.kt, Skyflow/src/main/kotlin/Skyflow/InsertOptions.kt, Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/RevealElementInput.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/main/kotlin/Skyflow/collect/client/CollectRequestBody.kt, Skyflow/src/main/kotlin/Skyflow/collect/client/CollectRequestRecord.kt, Skyflow/src/main/kotlin/Skyflow/reveal/RevealValueCallback.kt, app/src/main/java/com/Skyflow/MainActivity.kt, app/src/main/java/com/Skyflow/RevealActivity.kt
1.added additionalFields to collect
2.changed styles to inputStyles in CollectElementInput and RevealElementInput
=> added additional fields for collect and modified styles to inputStyles.

Skyflow/src/main/kotlin/Skyflow/BaseElement.kt, Skyflow/src/main/kotlin/Skyflow/CollectContainer.kt, Skyflow/src/main/kotlin/Skyflow/Element.kt, Skyflow/src/main/kotlin/Skyflow/ElementType.kt, Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/utils/CardType.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/ElementMatchRule.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/ElementValueMatchRule.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/LengthMatchRule.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/RegexMatchRule.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/SkyflowValidateCardNumber.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/SkyflowValidator.kt, Skyflow/src/main/kotlin/Skyflow/core/elements/state/StateforText.kt, Skyflow/src/main/kotlin/Skyflow/utils/Utils.kt, Skyflow/src/test/java/com/Skyflow/CollectTest.kt, Skyflow/src/test/java/com/Skyflow/InvokeConnectionTest.kt, Skyflow/src/test/java/com/Skyflow/UnitTests.kt, Skyflow/src/test/java/com/Skyflow/ValidationTests.kt, samples/README.md, samples/src/main/java/com/Skyflow/CollectActivity.kt, samples/src/main/java/com/Skyflow/GenerateCvv.kt, samples/src/main/java/com/Skyflow/PullFunds.kt, samples/src/main/java/com/Skyflow/RevealActivity.kt, samples/src/main/res/layout/activity_collect.xml, settings.gradle
added checks for length match for card type
=> Fix card validation

Skyflow/src/main/kotlin/Skyflow/CollectElementOptions.kt, Skyflow/src/main/kotlin/Skyflow/ElementType.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/utils/Spacespan.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/validations/SkyflowValidateExpireDate.kt, Skyflow/src/test/java/com/Skyflow/CollectTest.kt, Skyflow/src/test/java/com/Skyflow/ValidationTests.kt, samples/src/main/java/com/Skyflow/CollectActivity.kt
format pattern for cardNmuber and expirationDate
=> added format pattern for cardNumber and expirationDate

Skyflow/src/main/kotlin/Skyflow/BaseElement.kt, Skyflow/src/main/kotlin/Skyflow/Element.kt, Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/main/kotlin/Skyflow/collect/client/CollectRequestBody.kt, Skyflow/src/main/kotlin/Skyflow/reveal/RevealValueCallback.kt, Skyflow/src/test/java/com/Skyflow/CollectTest.kt, Skyflow/src/test/java/com/Skyflow/RevealTest.kt
added setError and resetError for collect and reveal elements
=> added setError and restError for collect and reveal elements

README.md
Signed-off-by: Shaik-Luqmaan <luqmaan.shaik@skyflow.com>
=> SDK-619/ Add security email in readme

CHANGELOG.md
=> SDK-709 update changelog file

Skyflow/src/test/java/com/Skyflow/CollectTest.kt, Skyflow/src/test/java/com/Skyflow/UnitTests.kt, samples/README.md, samples/data/vaultSchema.json, samples/src/main/java/com/Skyflow/CollectActivity.kt, samples/src/main/java/com/Skyflow/RevealActivity.kt
- Updated the sample app README with instructions on how to run the sample app.
- Fixed build failure/ test case failure issues
=> [SDK-757] Update sample apps readme

Skyflow/src/main/kotlin/Skyflow/collect/client/CollectAPICallback.kt, Skyflow/src/test/java/com/Skyflow/ResponseTest.kt
- Fixed inconsistency of error message being sent in response for pure `insert` and `collect` elements.
- Fixed Unit Test for inconsistent error messages in pure `insert` and `collect` methods.
=> SK-431 Consistent Error Messages format in Android SDK across all methods

Skyflow/src/main/kotlin/Skyflow/core/APIClient.kt
- Token was regenerated every 60 minutes instead of every 55 minutes
=> CUST-873 Fix Android SDK bug

Skyflow/build.gradle, Skyflow/src/main/kotlin/Skyflow/core/APIClient.kt
=> CUST-873 Release/23.3.1

Skyflow/src/main/kotlin/Skyflow/core/APIClient.kt
- Removed 5 mins grace period for cache refresh of bearer token
- Issue [SK-544](https://skyflow.atlassian.net/browse/SK-544)
[SK-544]: https://skyflow.atlassian.net/browse/SK-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-544 Removal of Grace Period of 5 mins

Skyflow/src/main/kotlin/Skyflow/reveal/RevealValueCallback.kt, Skyflow/src/main/kotlin/Skyflow/utils/Utils.kt
- Fixed the bug where if `invalid tokens` were set for multiple `Reveal Elements`, UI error would come only for one of the elements.
- Worked on [SK-565](https://skyflow.atlassian.net/browse/SK-565)
[SK-565]: https://skyflow.atlassian.net/browse/SK-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-565 Reveal Elements UI Error fix for Invalid Tokens

Skyflow/build.gradle, Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt, Skyflow/src/main/kotlin/Skyflow/RevealElementInput.kt, Skyflow/src/main/kotlin/Skyflow/reveal/RevealValueCallback.kt, Skyflow/src/main/kotlin/Skyflow/utils/Utils.kt, Skyflow/src/test/java/com/Skyflow/RevealTest.kt, Skyflow/src/test/java/com/Skyflow/SoapConnectionTest.kt
- #126
- #128
- [SK-536](https://skyflow.atlassian.net/browse/SK-536)
- [SK-565](https://skyflow.atlassian.net/browse/SK-565)
[SK-536]: https://skyflow.atlassian.net/browse/SK-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-565]: https://skyflow.atlassian.net/browse/SK-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-581/Release/23.3.2.2 patch

CHANGELOG.md
- Updated CHANGELOG till latest version `v1.18.4`
=> SK-660 Update CHANGELOG with latest version release in Android SDK

Skyflow/src/main/kotlin/Skyflow/reveal/RevealValueCallback.kt
- Fixed bug for same invalid tokens set for multiple reveal elements.
- Fixed bug for same valid tokens set for multiple reveal elements.
=> SK-583 Same Tokens set for Reveal Elements Bug

Skyflow/src/main/kotlin/Skyflow/CollectContainer.kt, Skyflow/src/main/kotlin/Skyflow/CollectElementOptions.kt, Skyflow/src/main/kotlin/Skyflow/ElementType.kt, Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/RevealElementOptions.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/utils/Spacespan.kt, Skyflow/src/main/kotlin/Skyflow/core/Messages.kt, Skyflow/src/main/kotlin/Skyflow/utils/Utils.kt, Skyflow/src/test/java/com/Skyflow/InputFormattingTest.kt
- [SK-592](https://skyflow.atlassian.net/browse/SK-592) Development of Input formatting support for collect elements.
- [SK-596](https://skyflow.atlassian.net/browse/SK-596) Unit Tests for Input formatting support for collect elements.
- [SK-663](https://skyflow.atlassian.net/browse/SK-663) Development of Input formatting support for reveal elements. 
- [SK-664](https://skyflow.atlassian.net/browse/SK-664) Unit Tests for Input formatting support for reveal elements.
[SK-592]: https://skyflow.atlassian.net/browse/SK-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-596]: https://skyflow.atlassian.net/browse/SK-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-663]: …
=> SK-234 Input Formatting in Android SDK

.github/workflows/beta_release.yml, .github/workflows/release.yml, Skyflow/build.gradle
- Added beta release workflow.
- Modified public release workflow to not triger for beta release.
- Modified build file to add a separate beta package.
=> SK-600 Beta Release For Input Formatting in Android SDK

Skyflow/build.gradle
This reverts commit c06cb10055eb20f2b6930dc217a67413f58dccb8.
=> SK-600 Revert "[AUTOMATED] Public Release 1.19.0-beta.1"

Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt, Skyflow/src/main/kotlin/Skyflow/RevealElementInput.kt, Skyflow/src/main/kotlin/Skyflow/core/APIClient.kt, Skyflow/src/main/kotlin/Skyflow/reveal/RevealApiCallback.kt, Skyflow/src/main/kotlin/Skyflow/reveal/RevealRequestBody.kt, Skyflow/src/main/kotlin/Skyflow/utils/Utils.kt, Skyflow/src/test/java/com/Skyflow/DetokenizeTests.kt, Skyflow/src/test/java/com/Skyflow/RevealTest.kt
- [SK-720](https://skyflow.atlassian.net/browse/SK-720) Development of Column group support in Android SDK
- [SK-721](https://skyflow.atlassian.net/browse/SK-721) Unit Tests for Column group support in Android SDK
- [SK-733](https://skyflow.atlassian.net/browse/SK-733) Fix Error message format for failure callback in Android SDK
[SK-338]: https://skyflow.atlassian.net/browse/SK-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-720]: https://skyflow.atlassian.net/browse/SK-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-721]: https://skyflow.atlassian.net/browse/SK-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-733]: …
=> SK-338 Column Group Support in Android SDK

.github/workflows/internal_release.yml, Skyflow/build.gradle
- Updated the Internal Release pipeline to select latest stable tag.
- Updated the `build.gradle` to publish a separate package for internal release.
=> SK-751 modify Internal Release process Android SDK

CHANGELOG.md, README.md, samples/src/main/java/com/Skyflow/RevealActivity.kt
- SK-722 Update README for Column Group Support changes in Android SDK
- SK-798 Update Samples w.r.t Column Group Support changes in Android SDK
=> SK-338 Update README, CHANGELOG, Samples for Column Group Support in Android SDK

CHANGELOG.md, README.md
- [SK-595](https://skyflow.atlassian.net/browse/SK-595)
[SK-595]: https://skyflow.atlassian.net/browse/SK-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-595 Update README for Input Formatting in Android SDK

Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/utils/Utils.kt
- Allows copy for reveal elements when they are revealed successfully.
=> ​SK-1105 Add copy functionality to Reveal Elements

CHANGELOG.md, README.md, samples/src/main/java/com/Skyflow/InputFormattingCollect.kt, samples/src/main/java/com/Skyflow/InputFormattingReveal.kt
- SK-1110 Updated README, CHANGELOG and Samples.
=> SK-1099 Customise Copy behaviour for Collect and Reveal Elements

README.md, samples/src/main/AndroidManifest.xml, samples/src/main/java/com/Skyflow/ComposableActivity.kt
- SK-832 Update README for Composable Elements in Android SDK
- SK-832 Update Sample for Composable Elements in Android SDK
- SK-462 Create sample app similar to Composable Elements
=> SK-344 Composable Elements in Android SDK

Skyflow/src/main/kotlin/Skyflow/TextField.kt
- When both `enableCardIcon` and `enablecopy` were set to `true` card icon was not visible.
=> SK-1137 Fix Bug - card icon not visible for Card Number element

Skyflow/src/main/kotlin/Skyflow/Label.kt, Skyflow/src/main/kotlin/Skyflow/Style.kt, Skyflow/src/main/kotlin/Skyflow/Styles.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/test/java/com/Skyflow/CollectTest.kt
- SK-1100 Test Driven Development of Styling enhancements
- SK-1162 Indicate required fields by asterisk `*` symbol
=> SK-997 Styling Enhancements in Android SDK

Skyflow/build.gradle, Skyflow/src/main/kotlin/Skyflow/CardMetadata.kt, Skyflow/src/main/kotlin/Skyflow/CollectElementOptions.kt, Skyflow/src/main/kotlin/Skyflow/TextField.kt, Skyflow/src/main/kotlin/Skyflow/collect/elements/utils/CardType.kt, Skyflow/src/main/kotlin/Skyflow/core/elements/state/StateforText.kt, Skyflow/src/main/res/drawable/ic_cartes_bancaires.xml, Skyflow/src/main/res/drawable/ic_dropdown.xml, Skyflow/src/test/java/com/Skyflow/CollectTest.kt, Skyflow/src/test/java/com/Skyflow/UnitTests.kt
- Public release for card brand choice
- To enable users to select card provider in case of `co-badged` cards
- Manual testing of feature and internal release version.
- Unit tests to cover scenarios. Whole flow will be covered in E2E tests
=> SK-1609/Release/24.9.1

CHANGELOG.md, README.md, samples/build.gradle, samples/src/main/AndroidManifest.xml, samples/src/main/java/com/Skyflow/CardBrandChoiceActivity.kt, samples/src/main/java/com/Skyflow/MainActivity.kt, samples/src/main/java/com/Skyflow/utils/CustomStyles.kt, samples/src/main/res/layout/activity_main.xml, samples/src/main/res/values/strings.xml
For every feature release, we
- update README with proper instructions and guidelines about the feature
- maintain a CHANGELOG to track all the releases
- provide a sample to help users get started with the new feature
- User will know about the newly released updates and their instructions and guidelines
- User can update vault and other required details to use this sample code for card brand choice.
- We will be able to track the releases with all the changes
=> SK-1608 Add sample for card brand choice in Android SDK

.github/pull_request_template.md
A PR template provides structure, making it easier for reviewers to understand the purpose, context, and changes made in the code. This template is typically used in repositories to ensure that every PR includes important details, such as a description, a reason, goals, and test coverage.
- By using a template, the format of PR descriptions remains consistent across the team, making it easier to review and understand.
- It prompts developers to provide necessary information, such as the purpose of the PR, relevant issues, and testing instructions, reducing confusion.
- The template ensures that all critical aspects of the code are documented, which helps the reviewer focus on the changes rather than looking for missing context.
- By including sections like "What is this PR solving?" and …
=> SK-1407 Add PR Template

.github/workflows/internal_release.yml
- Update actions/cache version from v2 to v4
=> SK-1929 bump actions cache version
